# Generated by Django 5.2.4 on 2025-07-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='chatbot_model',
            field=models.CharField(choices=[('gpt', 'gpt'), ('gemini', 'Gemini'), ('deepseek', 'geespsek'), ('groq', 'groq')], default='gpt', max_length=100),
        ),
        migrations.AddField(
            model_name='prompt',
            name='google_model',
            field=models.CharField(default='gemini-2.0-flash', max_length=100),
        ),
        migrations.AddField(
            model_name='prompt',
            name='variance_prompt',
            field=models.TextField(default=''),
        ),
    ]
