# Generated by Django 5.2.4 on 2025-07-27 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_prompt_chatbot_model_prompt_google_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prompt',
            name='chatbot_model',
            field=models.CharField(choices=[('gpt', 'gpt'), ('gemini', 'gemini'), ('deepseek', 'deepseek'), ('groq', 'groq')], default='gemini', max_length=100),
        ),
    ]
