# Generated by Django 5.2.4 on 2025-07-27 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_prompt_chatbot_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summarize_prompt', models.TextField()),
                ('sql_prompt', models.TextField()),
                ('response_prompt', models.TextField()),
                ('sql_response_prompt', models.TextField(default='')),
                ('chatbot_model', models.CharField(choices=[('gpt', 'gpt'), ('gemini', 'gemini'), ('deepseek', 'deepseek'), ('groq', 'groq')], default='gemini', max_length=100)),
                ('variance_prompt', models.TextField(default='')),
                ('google_model', models.CharField(default='gemini-2.0-flash', max_length=100)),
                ('views_model', models.CharField(default='gemini-2.0-flash', max_length=100)),
            ],
        ),
    ]
