# Generated by Django 5.2.4 on 2025-07-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_prompt1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ayo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Prompt1',
            new_name='Prompt7',
        ),
    ]
